apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
  labels:
    app: invoice-app-dpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
    spec:
      containers:
        - name: invoice-app
          image: sonam2606r/constants-backend:99
          ports:
          - containerPort: 4002
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                   name: db-config
                   key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DB_DATABASE
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-config
                  key: DB_PASSWORD
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-config
                  key: REDIS_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: NODE_ENV
      imagePullSecrets:
        - name: docker-cred

