apiVersion: v1
kind: Secret
metadata:
  name: db-config
type: Opaque
data:
  DB_HOST: Y29uc3RhbnRzLWJhY2tlbmQuY3hjcGZycjBsbXg4LmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb20=
  DB_USER: cm9vdA==
  DB_PASSWORD: bXktc2VjcmV0LXB3
  DB_DATABASE: aW52b2ljZXM=
  DB_PORT: MzMwNg==
